title: "Juba Agoun Associate"
baseurl: ""
url: "https://juba-agoun.github.io/en/index.html"

plugins:
  - jekyll-polyglot

languages: ["fr", "en"]
default_lang: "fr"
exclude_from_localization: ["assets", "favicon.ico"]
