title: "Juba Agoun Associate"
baseurl: ""
url: "https://juba-agoun.github.io/"

plugins:
  - jekyll-polyglot

defaults:
  - scope:
      path: "fr"
      type: "pages"
    values:
      lang: "fr"
  - scope:
      path: "en"
      type: "pages"
    values:
      lang: "en"
      
languages: ["fr", "en"]
default_lang: "en"
exclude_from_localization: ["assets", "favicon.ico"]
